"""Add authentication: password_hash, email, sessions table, user_id FK

Revision ID: 1052d2e36053
Revises: b8ab312fc9b8
Create Date: 2025-10-14 06:09:13.657834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1052d2e36053'
down_revision: Union[str, None] = 'b8ab312fc9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.add_column('generations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index('ix_generations_user_id', 'generations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'generations', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'generations', type_='foreignkey')
    op.drop_index('ix_generations_user_id', table_name='generations')
    op.drop_column('generations', 'user_id')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
