"""Add indexes to generations table

Revision ID: a8d0d774b4fe
Revises: c31bba7cdef1
Create Date: 2025-10-09 05:15:29.638428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d0d774b4fe'
down_revision: Union[str, None] = 'c31bba7cdef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_generations_created_at', 'generations', ['created_at'], unique=False)
    op.create_index('ix_generations_github_url', 'generations', ['github_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generations_github_url', table_name='generations')
    op.drop_index('ix_generations_created_at', table_name='generations')
    # ### end Alembic commands ###
