"""Add story and meme text fields to generations

Revision ID: b8ab312fc9b8
Revises: a8d0d774b4fe
Create Date: 2025-10-13 06:41:25.592983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ab312fc9b8'
down_revision: Union[str, None] = 'a8d0d774b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('story', sa.Text(), nullable=True))
    op.add_column('generations', sa.Column('meme_text_top', sa.String(length=100), nullable=True))
    op.add_column('generations', sa.Column('meme_text_bottom', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'meme_text_bottom')
    op.drop_column('generations', 'meme_text_top')
    op.drop_column('generations', 'story')
    # ### end Alembic commands ###
