"""Initial migration: create users and generations tables

Revision ID: c31bba7cdef1
Revises: 
Create Date: 2025-10-08 06:29:21.710401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c31bba7cdef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.Text(), nullable=False),
    sa.Column('repo_owner', sa.String(length=255), nullable=True),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('repo_size_kb', sa.Integer(), nullable=True),
    sa.Column('code_quality_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cat_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('generations')
    # ### end Alembic commands ###
